#YAML

name: inception

# TEMPLATES AND ANCHORS

x-common-service: &common-service
  init: true
  restart: always
  networks:
    - inception-backend

# SERVICES

services:
  mariadb:
    <<: *common-service
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    secrets:
      - mariadb_root_pass
      - mariadb_admin_pass
      - mariadb_wp_user_pass
    environment:
      - MARIADB_WP_DATABASE
      - MARIADB_ADMIN_USER
      - MARIADB_WP_USER
    image: mariadb:inception_mariadb
    container_name: mariadb
    volumes:
      - wp_db:/var/lib/mysql
    # use io_uring - high-performance Linux kernel feature for fast asynchronous disk operations.
    security_opt:
      - seccomp=unconfined  

  wordpress:
    <<: *common-service
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
      args:
        - WP_PHP_VERSION
        - WP_VERSION
    image: wordpress:inception_wp
    container_name: wordpress
    environment:
      - DOMAIN_NAME
      - WP_TITLE
      - WP_DB_HOST
      - WP_DB_NAME
      - WP_DB_USER
      - WP_ADMIN_USER
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_EMAIL
      - WP_PHP_VERSION
      - WP_VERSION
    secrets:
      - mariadb_wp_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - mariadb

  nginx:
    <<: *common-service
    build: ./requirements/nginx
    image: nginx:inception_nginx
    container_name: nginx
    # prort - outside: inside
    environment:
      - DOMAIN_NAME
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - wp_files:/var/www/html
      - v_nginx_cert:/etc/nginx/ssl 
    depends_on:
      - wordpress

# VOLUMES
volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      # If USER_LOG is not set, it defaults to 'default_user'
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/wp_files
  v_nginx_cert:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/v_nginx_cert

# NETWORKS
networks:
  inception-backend:
    driver: bridge

# SECRETS
secrets:
  mariadb_root_pass:
    file: ${MARIADB_ROOT_PASSWORD_HOST_FILE}
  mariadb_admin_pass:
    file: ${MARIADB_ADMIN_PASSWORD_HOST_FILE}
  mariadb_wp_user_pass:
    file: ${MARIADB_WP_USER_PASSWORD_HOST_FILE}
  
  wp_admin_pass:
    file: ${WP_ADMIN_PASSWORD_HOST_FILE}
  wp_user_pass:
    file: ${WP_USER_PASSWORD_HOST_FILE}