#YAML

name: inception

# TEMPLATES AND ANCHORS

x-common-service: &common-service
  init: true
  restart: always
  networks:
    - inception-backend

services:
  mariadb:
    <<: *common-service
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    secrets:
      - mariadb_root_pass
      - mariadb_admin_pass
      - mariadb_wp_user_pass
      - mariadb_exporter_pass
    environment:
      - MARIADB_WP_DATABASE
      - MARIADB_ADMIN_USER
      - MARIADB_WP_USER
    image: mariadb:inception_mariadb
    container_name: mariadb
    volumes:
      - wp_db:/var/lib/mysql
    # use io_uring - high-performance Linux kernel feature for fast asynchronous disk operations.
    security_opt:
      - seccomp=unconfined  

  wordpress:
    <<: *common-service
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
      args:
        - WP_PHP_VERSION
        - WP_VERSION
    image: wordpress:inception_wp
    container_name: wordpress
    environment:
      - DOMAIN_NAME
      - NGINX_PORT
      - WP_TITLE
      - WP_DB_HOST
      - WP_DB_NAME
      - WP_DB_USER
      - WP_ADMIN_USER
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_EMAIL
      - WP_PHP_VERSION
      - WP_VERSION
      - WP_REDIS_HOST
      - WP_REDIS_PORT
    secrets:
      - mariadb_wp_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - mariadb
      - redis

  nginx:
    <<: *common-service
    build: ./requirements/nginx
    image: nginx:inception_nginx
    container_name: nginx
    # prort - outside: inside
    environment:
      - DOMAIN_NAME
      - NGINX_PORT
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    #  - "8080:80"
    #  -  "4443:443"
    volumes:
      - wp_files:/var/www/html
      - v_nginx_cert:/etc/nginx/ssl 
    depends_on:
      - wordpress

  # -- bonus - vsftpd
  ftp:
    <<: *common-service
    build: ./requirements/ftp
    image: nginx:inception_ftp
    container_name: ftp
    environment:
      - DOMAIN_NAME
      - FTP_USER
    ports:
      - "1121:21"
      # - "1120:20"
      # - "20:20"
      # - "21:21"
      - "21000-21010:21000-21010"
    secrets:
      - ftp_user_pass
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD-SHELL", "pgrep vsftpd || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    <<: *common-service
    build: ./requirements/redis
    image: redis:inception_redis
    container_name: redis
    volumes:
      - v_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s    
  
  adminer:
    <<: *common-service
    build:
      context: ./requirements/adminer
      dockerfile: ./Dockerfile
      args:
        - A_PHP_VERSION
        - ADMINER_VERSION
    image: adminer:inception_adminer
    container_name: adminer
    environment:
      - A_PHP_VERSION
    ports:
      - "8080:8080"

  simple-site:
    <<: *common-service
    build:
      context: ./requirements/simple-site
      dockerfile: ./Dockerfile
    container_name: simple-site
    ports:
      - "8880:80"
  
  mariadb-exporter:
    <<: *common-service
    image: prom/mysqld-exporter:v0.20.0
    container_name: mariadb-exporter
    secrets:
      - mariadb_exporter_pass
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        cat > /tmp/.my.cnf <<EOF
        [client]
        user=prometheus
        password=$$(cat /run/secrets/mariadb_exporter_pass)
        EOF

        chmod 600 /tmp/.my.cnf

        exec /bin/mysqld_exporter \
          --config.my-cnf=/tmp/.my.cnf \
          --mysqld.address=mariadb:3306 \
          --web.listen-address=0.0.0.0:9104 \
          --no-collect.slave_status
    depends_on:
      - mariadb

  prometheus:
    <<: *common-service
    build:
      context: ./requirements/prometheus
      dockerfile: ./Dockerfile
    volumes:
      - v_prometheus_tsd:/var/lib/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - mariadb-exporter


# VOLUMES
volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      # If USER_LOG is not set, it defaults to 'default_user'
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/wp_files
  v_nginx_cert:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/v_nginx_cert
  v_redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/v_redis
  v_prometheus_tsd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-/home/${USER_LOG:-default_user}/data}/v_prometheus_tsd

# NETWORKS
networks:
  inception-backend:
    driver: bridge

# SECRETS
secrets:
  mariadb_root_pass:
    file: ${MARIADB_ROOT_PASSWORD_HOST_FILE}
  mariadb_admin_pass:
    file: ${MARIADB_ADMIN_PASSWORD_HOST_FILE}
  mariadb_wp_user_pass:
    file: ${MARIADB_WP_USER_PASSWORD_HOST_FILE}
  
  wp_admin_pass:
    file: ${WP_ADMIN_PASSWORD_HOST_FILE}
  wp_user_pass:
    file: ${WP_USER_PASSWORD_HOST_FILE}

  ftp_user_pass:
    file: ${FTP_USER_PASSWORD_HOST_FILE}

  mariadb_exporter_pass:
    file: ${MARIADB_EXPLORER_HOST_FILE}